Use javax.annotation-api from core
jenkinsci/plugin-util-api-plugin pull request #147
Opened 2021-12-22 15:21 UTC by basil

Noticed in jenkinsci/nodelabelparameter-plugin#76. The explicit dependency on javax.annotation-api causes Enforcer errors for other plugins with this plugin in their dependency chain (typically through matrix-project or junit) and is unnecessary because the plugin parent POM already adds a dependency on core which ships this library anyway.

2021-12-22 18:23 UTC, MarkEWaite approved these changes

2021-12-23 09:20 UTC, uhafner reviewed
Can you please remove it from line 149 as well (includeArtifactIds)?

2021-12-23 09:20 UTC, uhafner requested changes
Can you please remove it from line 149 as well (`includeArtifactIds`)?

2021-12-23 16:20 UTC, basil commented
> Can you please remove it from line 149 as well (`includeArtifactIds`)?

Done

2021-12-23 16:31 UTC, uhafner approved these changes

2021-12-23 16:31 UTC, merged